markdown: redcarpet2
lsi: false
source: source
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["mkfile"]
redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
  extensions: ["fenced_code_blocks"]
